In [109]:
import pandas as pd
import numpy as np
import plotly as plt
import plotly.plotly as py
import plotly.graph_objs as go

In [110]:
#importing the data into python
data=pd.read_csv("coredata_sh.csv",usecols = ['Employee Name', 'Employee Number', 'State', 'Zip',
       'DOB', 'Age', 'Sex', 'MaritalDesc', 'CitizenDesc', 'Hispanic/Latino',
       'RaceDesc', 'Date of Hire', 'Date of Termination', 'Reason For Term',
       'Employment Status', 'Department', 'Position', 'Pay Rate',
       'Manager Name', 'Employee Source', 'Performance Score', 'tenur',
       'attrition'])

In [111]:
data.columns

Index(['Employee Name', 'Employee Number', 'State', 'Zip', 'DOB', 'Age', 'Sex',
       'MaritalDesc', 'CitizenDesc', 'Hispanic/Latino', 'RaceDesc',
       'Date of Hire', 'Date of Termination', 'Reason For Term',
       'Employment Status', 'Department', 'Position', 'Pay Rate',
       'Manager Name', 'Employee Source', 'Performance Score', 'tenur',
       'attrition'],
      dtype='object')

In [62]:
data

,Employee Name,Employee Number,State,Zip,DOB,Age,Sex,MaritalDesc,CitizenDesc,Hispanic/Latino,...,Reason For Term,Employment Status,Department,Position,Pay Rate,Manager Name,Employee Source,Performance Score,tenur,attrition
0,"Lindsay, Leonara",602000312,CT,6070,10/5/1988,29,female,Single,US Citizen,Yes,...,N/A - still employed,Active,IT/IS,IT Support,26.00,Eric Dougall,Diversity Job Fair,Exceeds,NaN,No
1,"Dickinson, Geoff",706006285,MA,2180,11/15/1982,35,male,Single,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,21.00,Ketsia Liebig,Pay Per Click - Google,Fully Meets,NaN,No
2,"Kinsella, Kathleen",710007401,MA,2170,12/8/1973,44,female,Married,US Citizen,No,...,more money,Voluntarily Terminated,Production,Production Technician I,22.00,Webster Butler,Search Engine - Google Bing Yahoo,90-day meets,1347.0,Yes
3,"Rose, Ashley",710007555,MA,1886,12/5/1974,43,female,Separated,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,17.00,David Stanley,Website Banner Ads,Fully Meets,NaN,No
4,"Smith, Leigh Ann",711007713,MA,1844,6/14/1987,30,female,Married,US Citizen,No,...,career change,Voluntarily Terminated,Admin Offices,Administrative Assistant,20.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,730.0,Yes
5,"Ferreira, Violeta",803009012,MA,2176,6/10/1986,31,female,Single,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,23.00,Ketsia Liebig,Newspager/Magazine,Fully Meets,NaN,No
6,"Sewkumar, Nori",807010161,MA,2191,3/10/1975,42,female,Single,US Citizen,No,...,N/A - still employed,Leave of Absence,Production,Production Technician I,15.20,Webster Butler,Search Engine - Google Bing Yahoo,Fully Meets,NaN,Yes
7,"Simard, Kramer",808010278,MA,2110,2/8/1970,47,male,Married,US Citizen,Yes,...,N/A - still employed,Active,IT/IS,Database Administrator,30.20,Simon Roup,Employee Referral,90-day meets,NaN,No
8,"Ozark, Travis",812011761,NC,27229,5/19/1982,35,male,Single,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,55.00,John Smith,Website Banner Ads,90-day meets,NaN,No
9,"Kirill, Alexandra",903013071,MA,2127,10/8/1970,47,female,Married,US Citizen,No,...,more money,Voluntarily Terminated,Production,Production Technician I,24.00,Amy Dunn,Search Engine - Google Bing Yahoo,Fully Meets,105.0,Yes
10,"Semizoglou, Jeremiah",904013591,MA,1545,2/9/1983,34,male,Married,US Citizen,No,...,N/A - Has not started yet,Future Start,IT/IS,Sr. Network Engineer,53.80,Peter Monroe,On-campus Recruiting,N/A- too early to review,NaN,NaN
11,"Goble, Taisha",905013738,MA,2127,10/23/1971,46,female,Single,US Citizen,No,...,"no-call, no-show",Terminated for Cause,IT/IS,Database Administrator,48.50,Simon Roup,Glassdoor,Fully Meets,27.0,Yes
12,"Shepard, Anita",906014183,MA,1773,4/14/1981,36,female,Married,US Citizen,No,...,N/A - still employed,Active,IT/IS,Network Engineer,47.00,Peter Monroe,Vendor Referral,Fully Meets,NaN,No
13,"Mckenna, Sandy",909015167,MA,2184,1/7/1987,31,female,Married,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,24.00,Kissy Sullivan,Monster.com,Fully Meets,NaN,No
14,"Stanley, David",1000974650,MA,1803,12/17/1975,42,male,Divorced,US Citizen,No,...,N/A - still employed,Active,Production,Production Manager,53.00,Janet King,Monster.com,Needs Improvement,NaN,No
15,Jeremy Prater,1001084890,NV,89139,5/9/1974,43,male,Married,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,56.00,Lynn Daneault,Website Banner Ads,PIP,NaN,No
16,"Monterro, Luisa",1001103149,MA,2126,4/24/1970,47,female,Single,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician II,25.00,Kissy Sullivan,Billboard,Exceptional,NaN,No
17,"Darson, Jene'ya",1001109612,MA,2110,11/5/1978,39,female,Married,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,15.00,Elijiah Gray,Billboard,Fully Meets,NaN,No
18,"Lynch, Lindsay",1001138521,MA,1844,2/14/1973,44,female,Single,US Citizen,Yes,...,Another position,Voluntarily Terminated,Production,Production Technician I,19.00,Webster Butler,Diversity Job Fair,Exceeds,1468.0,Yes
19,"Guilianno, Mike",1001167253,TN,37129,2/9/1969,48,male,Single,US Citizen,No,...,relocation out of area,Voluntarily Terminated,Sales,Area Sales Manager,55.00,John Smith,Newspager/Magazine,Fully Meets,1334.0,Yes
20,"Ruiz, Ricardo",1001175250,MA,1915,1/4/1964,54,male,Divorced,US Citizen,No,...,hours,Voluntarily Terminated,IT/IS,IT Manager - DB,21.00,Jennifer Zamora,Diversity Job Fair,Fully Meets,1395.0,Yes
21,"Ybarra, Catherine",1001268402,MA,2458,5/4/1982,35,female,Single,US Citizen,No,...,Another position,Voluntarily Terminated,Production,Production Technician I,22.00,Brannon Miller,Search Engine - Google Bing Yahoo,PIP,2583.0,Yes
22,"Anderson, Carol",1001417624,MA,2169,9/8/1989,28,female,Divorced,US Citizen,No,...,return to school,Voluntarily Terminated,Production,Production Technician I,16.00,Webster Butler,Word of Mouth,N/A- too early to review,57.0,Yes
23,"Cole, Spencer",1001450968,MA,1880,8/12/1979,38,male,Single,US Citizen,No,...,performance,Terminated for Cause,Production,Production Technician I,15.00,Kissy Sullivan,MBTA ads,Needs Improvement,440.0,Yes
24,"King, Janet",1001495124,MA,1902,9/21/1954,63,female,Married,US Citizen,Yes,...,N/A - still employed,Active,Executive Office,President & CEO,80.00,Board of Directors,Pay Per Click - Google,Fully Meets,NaN,No
25,"Lunquist, Lisa",1001504432,MA,2324,3/28/1982,35,female,Single,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician II,26.10,Elijiah Gray,Glassdoor,Exceeds,NaN,No
26,"Good, Susan",1001549006,MA,1886,5/25/1986,31,female,Married,US Citizen,No,...,N/A - still employed,Leave of Absence,Production,Production Technician II,24.25,David Stanley,Professional Society,Fully Meets,NaN,Yes
27,"Sweetwater, Alex",1001644719,MA,2184,11/22/1966,51,male,Single,US Citizen,No,...,N/A - still employed,Active,Software Engineering,Software Engineering Manager,27.00,Jennifer Zamora,Search Engine - Google Bing Yahoo,Fully Meets,NaN,No
28,"Pitt, Brad",1001735072,MA,2451,11/23/1981,36,male,Single,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,17.00,David Stanley,Search Engine - Google Bing Yahoo,Fully Meets,NaN,No
29,"Oliver, Brooke",1001856521,MA,2492,2/11/1952,65,female,Married,US Citizen,No,...,unhappy,Voluntarily Terminated,Production,Production Technician II,25.00,Webster Butler,Newspager/Magazine,90-day meets,462.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,"Wallace, Courtney E",1410071026,MA,2478,11/14/1955,62,female,Married,US Citizen,No,...,Another position,Voluntarily Terminated,Production,Production Manager,33.50,Janet King,Diversity Job Fair,Fully Meets,98.0,Yes
272,"Sparks, Taylor",1410071137,MA,2093,7/20/1968,49,female,Married,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,16.00,Brannon Miller,Billboard,PIP,NaN,No
273,"Hernandez, Daniff",1410071156,MA,1960,8/7/1986,31,male,Married,US Citizen,No,...,"no-call, no-show",Terminated for Cause,IT/IS,Database Administrator,40.10,Simon Roup,Employee Referral,N/A- too early to review,6.0,Yes
274,"Gonzalez, Cayo",1411071212,MA,2108,9/29/1969,48,male,Divorced,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,16.00,Brannon Miller,Diversity Job Fair,Exceeds,NaN,No
275,"Strong, Caitrin",1411071295,MT,59102,5/12/1989,28,female,Married,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,54.00,John Smith,Professional Society,Fully Meets,NaN,No
276,"Fraval, Maruk",1411071302,CT,6050,8/28/1963,54,male,Single,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Monster.com,Fully Meets,NaN,No
277,"Daniele, Ann",1411071312,CT,6033,1/18/1952,66,female,Married,US Citizen,No,...,N/A - still employed,Leave of Absence,IT/IS,Sr. Network Engineer,54.10,Peter Monroe,Vendor Referral,Fully Meets,NaN,Yes
278,"Gonzalez, Juan",1411071324,MA,2128,10/12/1964,53,male,Married,US Citizen,No,...,career change,Voluntarily Terminated,Production,Production Technician II,29.00,Brannon Miller,Diversity Job Fair,PIP,399.0,Yes
279,"Peters, Lauren",1411071406,MA,1886,8/17/1986,31,female,Married,US Citizen,No,...,more money,Voluntarily Terminated,Production,Production Technician II,29.00,Ketsia Liebig,Pay Per Click - Google,Exceeds,264.0,Yes
280,"Gonzales, Ricardo",1411071481,ID,83706,10/12/1954,63,male,Married,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,55.50,John Smith,Monster.com,Fully Meets,NaN,No
281,"Turpin, Jumil",1411071506,MA,2343,3/31/1969,48,male,Married,Eligible NonCitizen,No,...,N/A - still employed,Active,IT/IS,Network Engineer,49.10,Peter Monroe,Employee Referral,N/A- too early to review,NaN,No
282,"Favis, Donald",1412071562,CT,6033,7/30/1964,53,male,Single,US Citizen,No,...,hours,Terminated for Cause,IT/IS,Sr. DBA,58.20,Simon Roup,Vendor Referral,Fully Meets,732.0,Yes
283,"Leruth, Giovanni",1412071660,UT,84111,12/27/1988,29,male,Separated,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,55.00,John Smith,Website Banner Ads,Fully Meets,NaN,No
284,"Jhaveri, Sneha",1412071713,MA,2109,4/13/1964,53,female,Separated,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,19.00,Kelley Spirea,On-campus Recruiting,Fully Meets,NaN,No
285,"Biden, Lowan M",1412071844,MA,2027,12/27/1958,59,female,Divorced,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,22.00,Ketsia Liebig,Billboard,Fully Meets,NaN,No
286,"Smith, John",1499902910,MA,1886,8/16/1984,33,male,Divorced,US Citizen,no,...,N/A - still employed,Active,Sales,Sales Manager,56.00,Debra Houlihan,Diversity Job Fair,Needs Improvement,NaN,No
287,"Robertson, Peter",1499902991,MA,2138,7/3/1972,45,male,Married,US Citizen,No,...,Another position,Voluntarily Terminated,Production,Production Technician II,22.00,Kissy Sullivan,Glassdoor,Fully Meets,218.0,Yes
288,"Smith, Sade",1501071909,MA,2130,2/2/1965,53,female,Single,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,24.50,Ketsia Liebig,Employee Referral,Fully Meets,NaN,No
289,"Galia, Lisa",1501072093,CT,6040,7/6/1968,49,female,Single,US Citizen,No,...,N/A - still employed,Active,IT/IS,IT Support,31.40,Eric Dougall,Vendor Referral,Fully Meets,NaN,No
290,"Desimone, Carl",1501072124,MA,2061,4/19/1967,50,male,Married,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,20.00,Amy Dunn,Professional Society,PIP,NaN,No
291,"Onque, Jasmine",1501072180,FL,33174,5/11/1990,27,female,Single,US Citizen,Yes,...,N/A - still employed,Active,Sales,Area Sales Manager,57.00,Lynn Daneault,Pay Per Click - Google,Fully Meets,NaN,No
292,"Gentry, Mildred",1501072192,MA,2145,10/1/1990,27,female,Married,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,19.00,Michael Albert,Professional Society,N/A- too early to review,NaN,No
293,"Albert, Michael",1501072311,MA,2169,10/10/1968,49,male,Divorced,US Citizen,No,...,N/A - still employed,Active,Production,Production Manager,54.50,Janet King,Employee Referral,Fully Meets,NaN,No
294,"Ferguson, Susan",1502072511,MA,2176,4/14/1955,62,female,Married,US Citizen,No,...,military,Voluntarily Terminated,Production,Production Technician I,20.00,Webster Butler,Search Engine - Google Bing Yahoo,Fully Meets,922.0,Yes
295,"Riordan, Michael",1502072711,ND,58782,1/15/1968,50,male,Separated,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Billboard,Exceeds,NaN,No
296,"Jacobi, Hannah",1503072857,MA,1778,3/22/1966,51,female,Divorced,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,21.00,Kissy Sullivan,Employee Referral,Fully Meets,NaN,No
297,"Buck, Edward",1504073313,MA,2330,7/7/1975,42,male,Married,US Citizen,No,...,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Employee Referral,Fully Meets,NaN,No
298,"Bunbury, Jessica",1504073368,VA,21851,6/1/1964,53,female,Married,Eligible NonCitizen,No,...,Another position,Voluntarily Terminated,Sales,Area Sales Manager,55.00,John Smith,Social Networks - Facebook Twitter etc,Fully Meets,1083.0,Yes
299,"Cockel, James",1599991009,MA,2452,9/8/1977,40,male,Single,US Citizen,No,...,N/A - still employed,Active,Production,Production Technician I,15.00,David Stanley,Employee Referral,Fully Meets,NaN,No
300,"Gonzalez, Maria",1988299991,MA,2472,4/16/1981,36,female,Separated,US Citizen,Yes,...,N/A - still employed,Active,IT/IS,Network Engineer,39.00,Peter Monroe,Employee Referral,Fully Meets,NaN,No

In [112]:
data.dtypes

Employee Name           object
Employee Number          int64
State                   object
Zip                      int64
DOB                     object
Age                      int64
Sex                     object
MaritalDesc             object
CitizenDesc             object
Hispanic/Latino         object
RaceDesc                object
Date of Hire            object
Date of Termination     object
Reason For Term         object
Employment Status       object
Department              object
Position                object
Pay Rate               float64
Manager Name            object
Employee Source         object
Performance Score       object
tenur                  float64
attrition               object
dtype: object

In [166]:
data1=data.loc[data.attrition == "Yes",['Department']]
#data.loc[data.attrition == "Yes"]

In [167]:
xy=data1.Department.value_counts()

In [170]:
data2 = [go.Bar(
            x=data1.Department.unique(),
            y=xy
    )]
py.iplot(data2, filename='basic-bar')